### ISSUE TITLE
你不知道的CSS（一）

### ISSUE THREAD

**Issue by ly2011** [ly2011/blog#25]
## 用 `~` / `+` 兄弟选择器来美化表达元素

```
**选择器解析**
- `~` 选择器：查找某一个元素的后面的所有兄弟元素
- `+` 选择器：查找某一个元素的后面紧邻的兄弟元素
```

- switch 开关

- radio 美化

demo:

```html
  <div class="container goods-info">
    <div class="row goods-tags">
      <div class="col-md-2 tag-label">选择版本</div>
      <div class="col-md-10">
        <div class="tags-select">
          <label class="tag-select">
            <input type="radio" name="version" value="1">
            <span class="name">全网通(2GB 16GB)</span>
          </label>
          <label class="tag-select">
            <input type="radio" name="version" value="2">
            <span class="name">全网通(3GB 32GB)</span>
          </label>
          <label class="tag-select">
            <input type="radio" name="version" value="3" disabled>
            <span class="name">联通版(2GB 16GB)</span>
          </label>
        </div>
      </div>
    </div>
    <div class="row goods-tags">
      <div class="col-md-2 tag-label">购买方式</div>
      <div class="col-md-10">
        <div class="tags-select">
          <label class="tag-select">
            <input type="radio" name="bye-type" value="1">
            <span class="name">官方标配</span>
          </label>
          <label class="tag-select">
            <input type="radio" name="bye-type" value="2">
            <span class="name">移动优惠购</span>
          </label>
          <label class="tag-select">
            <input type="radio" name="bye-type" value="3" disabled>
            <span class="name">联通优惠购</span>
          </label>
          <label class="tag-select">
            <input type="radio" name="bye-type" value="4">
            <span class="name">电信优惠购</span>
          </label>
        </div>
      </div>
    </div>
  </div>

```

```scss
.goods-info {
  margin-top: 50px;
  margin-bottom: 50px;

  .tag-label {
    padding-top: 7px;
  }

  .goods-tags {
    margin-top: 2rem;
  }
}

.tags-select {
  font-size: 0;

  > .tag-select {
    display: inline-block;
    font-size: 14px;
    margin: 5px;
    position: relative;
    font-weight: normal;

    .name {
      display: block;
      line-height: 20px;
      padding: 8px 10px;
      border: 1px solid #ccc;
      cursor: pointer;
    }

    input[type='radio'] {
      position: absolute;
      opacity: 0;
      z-index: -1;

      &:checked + .name {
        border-color: #e3393c;
      }

      &:disabled + .name {
        background: #eee;
        color: #999;
        cursor: not-allowed;
      }
    }
  }
}
```

- checkbox 美化

## 用 `font-size: 0` 来清除间距

`inline-block` 的元素之间会受空白区域的影响，也就是元素之间差不多会有一个字符的空隙。你可以利用元素浮动`float`， 或者压缩html、清除元素间的空格来解决。但最简单有效的方法还是设父元素的 `font-size` 属性为 `0`。

demo:

```scss
* {
  box-sizing: border-box;
}

.items {
  font-size: 0;

  > .item {
    display: inline-block;
    width: 25%;
    height: 50px;
    border: 1px solid #ccc;
    text-align: center;
    line-height: 50px;
    background-color: #eee;
    font-size: 16px; // 不要忘了给子元素设置字号
  }
}

```

```html
  <div class="items">
    <div class="item">1</div>
    <div class="item">2</div>
    <div class="item">3</div>
    <div class="item">4</div>
  </div>
```

## 用 `boder` 来绘制三角形

```
**原理：**
只需要将其他三个边的颜色设置为透明(`transparent` 或者 `rgba(0, 0, 0, 0)`)，就会只保留一个三角形了。

## 用垂直方向的 `padding` 来实现等比缩放的盒子

固定图片百分比是一个针对响应式布局很有效的方案。简单来说，就是根据容器的宽度，按照宽高比例自动计算出容器的大小，并且让容器内的如 `img` 等子元素自适应宽高。

假设图片的比例是 4:3:
图片父容器宽度 100%，父容器的高度百分比为：`100 * 3 / 4 = 75%`；图片 `absolute` 并且完全铺满父容器。

```scss
.image-aspect-ratio {
  width: 100%;
  position: relative;
  padding-top: 75%;

  > img {
    width: 100%;
    height: 100%;
    position: absolute;
    top: 0;
    left: 0;
  }
}

```

```html
 <figure class="image-aspect-ratio">
    <img src="http://via.placeholder.com/640x384">
 </figure>
```

## 用 `pointer-event` 来禁用事件

`pointer-event` 属性更像是一个 JavaScript 事件，利用该属性，可以做以下事情：

- 阻止任何点击动作的执行
- 使链接显示为默认光标(`cursor: default`)
- 阻止触发 `hover` 和 `active` 状态
- 阻止 JavaScript 点击事件的触发

```css
// 使用该类，任何点击事件将无效
.disabled { pointer-events: none;} 
```

## 用`max-width`来防止图片撑破容器

```css
img {
    display: inline-block;
    max-width: 100%;
}
```

## 未知高度容器的多种垂直居中方法

在已知父子高度的情况下，实现垂直居中是很容易的事。`margin`、`padding`、`absolute + 负margin`，甚至 `line-height` 都是可行的方案。

这里主要介绍在父容器高度固定，子容器高度自适应的情况下，来实现其垂直居中于父盒子的几种方案。

html结构：

```html
  <div class="container-fluid">
    <div class="row">
      <!-- :before -->
      <div class="col-md-6">
        <div class="vh-modal vh-modal-1">
          <div class="vh-modal-content">
            <h3 class="vh-modal-title">模态框</h3>
            <div class="vh-modal-body">
              <h4>（伪）元素占位</h4>
              <p>使用（伪）元素占位法可以实现子元素在父元素上的垂直居中，然后利用父元素设置
                <code>text-align: center</code>实现水平居中，这是一种有效的实现水平垂直居中的方案</p>
            </div>
            <div class="vh-modal-foot">
              <button class="btn btn-primary">确定</button>
            </div>
          </div>
        </div>
      </div>

      <!-- transform -->
      <div class="col-md-6">
        <div class="vh-modal vh-modal-2">
          <div class="vh-modal-content">
            <h3 class="vh-modal-title">模态框</h3>
            <div class="vh-modal-body">
              <h4>absolute + transform</h4>
              <p>
                <span>利用
                  <code>absolute</code>绝对定位和css3的
                  <code>transform</code>位移属性配合，也可以实现子元素在父元素上的水平垂直居中。但是，如果子元素已经在高度上超过视窗高度，那它的顶部会被浏览器窗口裁掉。</span>
              </p>
            </div>
            <div class="vh-modal-foot">
              <button class="btn btn-primary">确定</button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <!-- table -->
      <div class="col-md-12">
        <div class="vh-modal vh-modal-3">
          <div class="vh-modal-cell">
            <div class="vh-modal-content">
              <h3 class="vh-modal-title">模态框</h3>
              <div class="vh-modal-body">
                <h4>table-cell</h4>
                <p>
                  利用div模拟table属性，也是一种很实用的实现子元素垂直居中的方法，确定是table的不可控属性以及要给子元素再包裹一层父元素
                </p>
              </div>
              <div class="vh-modal-foot">
                <button class="btn btn-primary">确定</button>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="row">
      <!-- flex -->
      <div class="col-md-6">
        <div class="vh-modal vh-modal-4">
          <div class="vh-modal-content">
            <h3 class="vh-modal-title">模态框</h3>
            <div class="vh-modal-body">
              <h4>flex</h4>
              <p>
                在移动端中优先推荐
                <code>flex</code>方案，目前，除了部分机型的UC浏览器，
                <code>flex</code>在手机浏览器中已经得到了很好的支持。
              </p>
            </div>
            <div class="vh-modal-foot">
              <button class="btn btn-primary">确定</button>
            </div>
          </div>
        </div>
      </div>

      <!-- flex+margin:auto -->
      <div class="col-md-6">
        <div class="vh-modal vh-modal-5">
          <div class="vh-modal-content">
            <h3 class="vh-modal-title">模态框</h3>
            <div class="vh-modal-body">
              <h4>flex+margin:auto</h4>
              <p>
                当子元素处于
                <code>flex</code>盒模型中，仅仅给子元素设置一个
                <code>margin:auto</code>的属性也完全可以实现水平和垂直方向的垂直居中，很神奇对吧？
              </p>
            </div>
            <div class="vh-modal-foot">
              <button class="btn btn-primary">确定</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
```

- (伪)元素占位方案（`推荐`）
利用 （伪）元素和 `display: inline-block` 的方案来实现垂直居中。

```scss
.vh-modal-1 {
  text-align: center;
  font-size: 0;

  &::before,
  > .vh-modal-content {
    display: inline-block;
    vertical-align: middle;
    font-size: 14px;
  }

  &::before {
    content: '';
    height: 100%;
  }
}
```
![default](https://user-images.githubusercontent.com/24327880/38793105-647cb872-4182-11e8-914d-4ba8b493ac46.png)

如上图中的 `::before` 你也可以使用一个真实的元素代替。

- absolute + transform 方案

使用 `absolute` 决定定位子元素，并且设置其 `top:50%;left:50%`，然后再利用 `css3` 的 `transform: translate(-50%, -50%);` 设置负值偏移回来也是一种有效的垂直居中方案，但是要**注意其兼容性以及不要将子元素置于父容器半个像素的位置上（如 500.5px），否则子容器会出现模糊**。

```scss
.vh-modal-2 {
  > .vh-modal-content {
    // 尽可能的不要让该元素的宽度出现奇数，否则可能会导致模糊
    display: inline-block; // 为了自适应宽度，也可以固定宽度
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
  }
}
```
`transform` 法还有一个缺点，就是当子元素容器高度超出视窗高度的时候，它会被直接截断（如下图），而不是想象中的随着浏览器滚动到顶部而滚动显示完全（模态框的头部被截掉了）。

![default](https://user-images.githubusercontent.com/24327880/38793347-7be27c62-4183-11e8-8baa-009622789c7c.png)

- table-cell 方案
使用div来模拟`table`的行为也可以实现垂直居中。缺点是要在子容器外层再包裹一个父元素`vh-modal-cell`用来模拟`table-cell`。

```scss
// table-cell
.vh-modal-3 {
  display: table;
  width: 100%;

  .vh-modal-cell {
    display: table-cell;
    vertical-align: middle;
    text-align: center;
  }

  .vh-modal-content {
    display: inline-block;
  }
}
```

```html
<div class="vh-modal vh-modal-3">
  <div class="vh-modal-cell">
    <div class="vh-modal-content">
       ...
    </div>
  </div>
</div>
<!-- 
模拟了table布局
<table style="width: 100%;">
  <tr>
      <td style="text-align: center; vertical-align: middle;">
          类似于直接使用table布局
      </td>
  </tr>
</table>
-->
```

- 基于 flex 的方案 `强烈推荐`

毫无疑问，`flex` 盒模型是最佳的实践方案。目前几乎所有现代浏览器都支持 `flex` 布局，尤其是移动端（部分机型UC浏览器效果太差）。基于 `flex` 盒模型的水平垂直居中有如下两种方案：

```html
<div class="vh-modal vh-modal-4(5)">
          <div class="vh-modal-content">
            ...
          </div>
</div>
```

**align-items & justify-content 方案**

```scss
.vh-modal-4 {
  display: flex;
  align-items: center;
  justify-content: center;

  > .vh-modal-content {
  }
}
```

**flex + margin 方案**
这个方案是最神奇的，仅仅给子元素设置了 `margin: auto;` 属性，一切就这么发生了。

```scss
.vh-modal-5 {
  display: flex;
  margin: 0;

  > .vh-modal-content {
    margin: auto;
  }
}
```

## 用 `counter` 来模拟/装饰有序清单
![default](https://user-images.githubusercontent.com/24327880/38794614-5021b71e-4188-11e8-8da5-56f16e2edb81.png)

类似于截图中这种多层级的数字，我们大概第一反应就是使用 `JavaScript` 循环列表，利用其 `index` 拼接而成的。事实上，仅仅使用 css 的 `counter` 属性也可以实现该功能，甚至实现起来更高效。

```scss
ol {
  counter-reset: decimal; /* 为每个ol元素创建新的计数器实例， 重置计数器成0 */
  list-style-type: none; // 去掉默认的list-style
  margin-left: 2rem;

  li {
    &::before {
      counter-increment: decimal; /* 只增加计数器的当前实例 */
      content: counters(decimal, '.') ' '; /* 显示计数器，并且为所有计数器实例增加以"."分隔的值 */
    }
  }
}

```
CSS计数器是CSS2.1中自动计数编号部分的实现。作为由CSS维护的变量，counter属性还有很多有趣的使用场景，具体就不展开了。请参考MDN上的 [使用CSS计数器章节](https://developer.mozilla.org/zh-CN/docs/Web/Guide/CSS/Counters)。

## 用 `table-layout` 来控制表格单元格宽度
你也许遇到过给表格设置了宽度，但是不起作用的问题。这是因为单元格的宽度是根据其内容进行调整的。刨根到底，是因为表格有个叫做 `table-layout` 的属性，其浏览器默认值是 `auto` 在作怪。当我们把这个值设置为 `fixed` 的时候，我们给 `th/td` 标签设置的宽度就起作用了。用法很简单：

```scss
table {
  table-layout: fixed;
  width: 100%;
}
![](https://img.smohan.net/9563fb79d019dcbc0e81875ca258c8ad.png?imageView2/1/interlace/1/q/100)
```

截图是设置table-layout: fixed;前后对比图，左边用蓝色标注的是默认行为的表格，右边是设置了table-layout: fixed;后的样式。显而易见的，默认情况下，单元格宽度受其内容约束。而设置了table-layout: fixed;后，其单元格宽度变得可控了。

```scss
.table {
  width: 100%;

  &.fixed {
    table-layout: fixed;
  }

  td.overflow {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
}

```

```html
  <div class="container-fluid">
    <!-- row -->
    <div class="row">
      <div class="col-md-6">
        <table class="table">
          <thead>
            <tr>
              <th width="10%">#</th>
              <th width="20%">用户</th>
              <th width="70%">内容</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td class="overflow">10086@qq.com@163.com@360.com</td>
              <td>通过为表格中的一行或一个单元格添加颜色而赋予不同的意义只是提供了一种视觉上的表现，并不能为使用辅助技术 -- 例如屏幕阅读器 -- 浏览网页的用户提供更多信息。因此，请确保通过颜色而赋予的不同意义可以通过内容本身来表达（即在相应行或单元格中的可见的文本内容）；或者通过包含额外的方式
                -- 例如应用了 .sr-only 类而隐藏的文本 -- 来表达出来</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col-md-6">
        <table class="table fixed">
          <thead>
            <tr>
              <th width="10%">#</th>
              <th width="20%">用户</th>
              <th width="70%">内容</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td class="overflow">10086@qq.com@163.com@360.com</td>
              <td>通过为表格中的一行或一个单元格添加颜色而赋予不同的意义只是提供了一种视觉上的表现，并不能为使用辅助技术 -- 例如屏幕阅读器 -- 浏览网页的用户提供更多信息。因此，请确保通过颜色而赋予的不同意义可以通过内容本身来表达（即在相应行或单元格中的可见的文本内容）；或者通过包含额外的方式
                -- 例如应用了 .sr-only 类而隐藏的文本 -- 来表达出来</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
```

## 用 `caret-color` 来定义光标的样式
在文本框中 `input/textarea` 中如果要改变光标的颜色，可以通过设置文本的颜色 `color: #f00` 来搞定。但是假如我们只想改变光标的颜色，而不想改变文本的颜色的话，`caret-color` 属性是屎一个实现方案。
![default](https://user-images.githubusercontent.com/24327880/38796785-0b868ff6-418f-11e8-9d7e-751bfb15a232.png)

```html
  <input type="text" value="I have a custom caret color!">
```
```scss
input {
  padding: 20px;
  font-size: 18px;
  width: 100%;
  display: block;
}
input,
textarea,
[contenteditable] {
  caret-color: red;
}

```

## 用 `user-select` 来禁用文本选中
在现在浏览器中，只需要一句 `user-select: none` 的css样式就可以解决。`IE6-9不支持` 该属性，可以通过给 `body` 添加 `onselectstart="return false;"` 的内联 `JavaScript` 语句搞定。

```scss
body {
  user-select: none;
}
```

## 参考文档

1. [你不知道的CSS（一）](https://smohan.net/blog/6gr77h)
