### ISSUE TITLE
避免内容跳动

### ISSUE THREAD

**Issue by ly2011** [ly2011/blog#33]
# 避免内容跳动

## 图片定宽高
最简单的方法是，给你将要加载的图片在样式里写好宽高，这样在加载完样式时就已经直到资源图片的占位。

### padding-bottom
然而到了移动端，需要适配不同的屏幕，图片就不能写死宽高了，我们希望它撑满宽度，高度自适应。可以使用 `padding-bottom` 或 `padding-top` 设置百分比来 hack。

```scss
@mixin aspect-ratio($width, $height) {
  position: relative;
  padding-bottom: ($height / $width) * 100%;
  img,
  video,
  iframe,
  object,
  embed {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
  }
}
```

```css
.ratio-sixteen-nine {
  @include aspect-ratio(1600, 900);
}
```

```html
<figure class="ratio-sixteen-nine">
  <img src="waterfall.jpg" alt="Waterfall in Iceland">
</figure>
```

> tips: 当你设置 padding 或者 margin 垂直方向为百分比时，它们的参照物是包含块的宽度，不是高度！不是高度！不是高度！

## 动态内容

还有些时候，我们并不知道将要加载的内容是什么，无法提前获取资源的信息。这种情况也能稍微补救一下，比如说给资源设置一个 min-height 避免大幅度跳动、或者加上一个 transition ，加载前宽度设为 0, 加载完成之后，高度自适应，让用户知道接下来目光要转向何处。

## font-weight 改变文字宽度
还有一种是修改文字粗细时，容易导致宽度增大，引起的文本跳动。

![](https://ohc0m0ub0.qnssl.com/text-jump.gif)

解决方法可以是使用伪元素来撑开宽度，然后将其隐藏。

```css
.bar:hover {
  font-weight: bold;
}

.bar:after {
  display: block;
  content: attr(data-title);
  font-weight: bold;
  height: 1px;
  color: white;
  color: transparent;
  overflow: hidden;
  visibility: hidden;
}
```

## 推荐阅读

- [content-jumping-avoid](https://css-tricks.com/content-jumping-avoid/)
- [ways-to-reduce-content-shifting-on-page-load](https://www.smashingmagazine.com/2016/08/ways-to-reduce-content-shifting-on-page-load/?sukey=3997c0719f1515207e17575c1c28cc39a9a7ea182e5e6516cd6750b49070a68835ff2b1fdef18154932f2fad626ebcc7)

## 参考文档

1. [避免内容跳动](https://www.w3ctrain.com/2016/09/05/avoid-content-jump/#more)
