### ISSUE TITLE
关于CSS变量的一些总结

### ISSUE THREAD

**Issue by ly2011** [ly2011/blog#46]
### 定义 CSS 变量

CSS 中，一个 CSS 变量是任意一个以`两个破折号开头`的“属性”值，

```css
.block {
  color: #8cacea;
  --color: blue;
}
```

CSS 变量也称作“自定义属性”

### CSS 变量作用域

CSS 变量都有一个作用域。

```css
:root {
  --main-color: red;
}
```

`:root` 选择器能让我们选择 DOM 树里最顶级的元素，也就是文档树。所有这样定义的变量，也就相当于全局变量了。
PS: 如何在局部和全局范围内定义变量

### 使用 CSS 变量

变量定义且被赋值后，你就可以使用它了。
需要使用 `var()` 这个函数引用变量。

```css
:root {
  --font-size: 20px;
}
.test {
  font-size: var(--font-size);
}
```

CSS 的变量需要非常小心谨慎，如果需要你还能做数学运算。多数情况下你应该把它们当作属性来使用。

```css
/* 下面这样是不对的 */
.margin {
  --side: margin-top;
  var(--side): 20px;
}
```

这样定义会抛出无效属性名的语法错误
你也无法直接使用数学运算功能。运算功能需要使用 `calc()` 函数。

```css
.margin {
  --space: 20px * 2;
  font-size: var(--space); // 这不是 40px
}
```

如果你一定需要使用数学计算，那么请使用 `calc()` 函数，如下：

```css
.margin {
  --space: calc(20px * 2);
  font-size: var(--space); /* 等于 40px */
}
```

### 值得一提的属性

有一些行为是值得提醒注意的。

#### 1. 自定义属性是普通属性值，因此它们可以定义在任意元素上。

在段落 p 元素，section，aside 元素或者 root 根元素，甚至是伪元素上使用变量，都是可以的。
它们和普通属性一样工作

#### 2.CSS 变量和普通 CSS 继承和叠加的规则相同

```css
div {
  --color: red;
}
div.test {
  color: var(--color);
}
div.ew {
  color: var(--color);
}
```

和普通变量相同，`--color`的值也会从其他的 div 元素继承下来。

#### 3. CSS 变量也可以和 `@media` 或其他条件选择的规则同时使用

和其他属性一样，你也可以使用 `@media` 或其他的条件规则里使用变量。
例如，下面的代码改变 变量的值，在不同的设备上使用不同值。

```css
:root {
  --gutter: 10px;
}
@media screen and (min-width: 768px) {
  -gutter: 30px;
}
```

#### 4. CSS 变量可以在 HTML 的 style 属性中使用

你也可以在内联样式里使用变量，它们也正常工作。

```html
<html style="--color: red;">

body {
  color: var(--color);
}
```

PS: CSS 变量大小写敏感。

```css
/* 这是两个不同的变量 */
:root {
  --color: blue;
  --COLOR: red;
}
```

### 解决多重定义

和其他属性是一样，重定义变量也遵循标准级联规则。
下面来看个例子：

```css
/* 变量定义 */
:root {
  --color: blue;
}
div {
  --color: green;
}
#alert {
  --color: red;
}

/*使用变量*/
* {
  color: var(--color);
}
```

有了上面的定义，不同的元素的值是什么样的呢？

```html
<p>我的颜色是？</p>
<div>我的呢？</div>
<div id="alert">
  我的颜色是？
  <p>颜色？</p>
</div>
```

第一个 p 元素是 `blue`, 没有任何 `--color` 变量定义是在 `p` 元素的，因此它会继承自根元素 `:root`。
第一个 `div` 是绿色 green。在`div`上有一个颜色变量定义。

```css
div {
  --color: green;
}
```

使用 ID 值为 `alert` 定义的 `div`, 不是绿色，而是红色 `red`。

```css
#alert {
  color: red;
}
```

### 解决循环依赖

循环依赖通常会在下面几种情况下发生：
1

### 参考文档

1. [关于 CSS 变量你需要知道的一切](https://www.zcfy.cc/article/everything-you-need-to-know-about-css-variables)
