### ISSUE TITLE
【布局】CSS布局方案

### ISSUE THREAD

**Issue by ly2011** [ly2011/blog#51]
# 【布局】CSS 布局方案

[TOC]

## 居中布局

> 以下布局均以不定宽为前提，定宽情况包含其中

### 1、水平居中

![](https://camo.githubusercontent.com/673ab0a72401c355da6b91ec43d41ec8e33eb92f/687474703a2f2f75706c6f61642d696d616765732e6a69616e7368752e696f2f75706c6f61645f696d616765732f313439343930382d626665356361623661616131616138382e706e673f696d6167654d6f6772322f6175746f2d6f7269656e742f7374726970253743696d61676556696577322f322f772f31323430)

#### 1.1 inline-block + text-align

```css
.parent {
  text-align: center;
}
.child {
  display: inline-block;
}
```

> tips: 此方案兼容性较好，可兼容至 IE8,对于 IE567 并不支持 inline-block,需要使用 css hack 进行兼容。

#### 1.2 table + margin

```css
.child {
  display: table;
  margin: 0 auto;
}
```

> tips: 此方案兼容至 IE8,可以使用`<table/>`代替 css 写法，兼容性良好。

#### 1.3 absolute + transform

```css
.parent {
  position: relative;
  height: 1.5em;
}
.child {
  position: absolute;
  left: 50%;
  transform: translateX(-50%);
}
```

> tips: 此方案兼容至 IE9,因为 transform 兼容性限制，如果`.child`为定宽元素，可以使用以下写法，兼容性极佳。

```css
.parent {
  position: relative;
  height: 1.5em;
}
.child {
  position: absolute;
  width: 100px;
  left: 50%;
  margin-left: -50px;
}
```

#### 1.4 flex + justify-content

```css
.parent {
  display: flex;
  justify-content: center;
}
.child {
  margin: 0 auto;
}
```

> tips: 移动端兼容性良好

### 2.垂直居中

![](https://camo.githubusercontent.com/bdd0ecded3d601ba4e401482a5805cedd4b6fbe5/687474703a2f2f75706c6f61642d696d616765732e6a69616e7368752e696f2f75706c6f61645f696d616765732f313439343930382d303936346463666539383536376530342e706e673f696d6167654d6f6772322f6175746f2d6f7269656e742f7374726970253743696d61676556696577322f322f772f31323430)

#### 2.1 table-cell + vertical-align

```css
.parent {
  display: table-cell;
  vertical-align: middle;
}
```

> tips: 可替换为 `<table/>` 布局，兼容性良好。

#### 2.2 absolute + transform

```css
.parent {
  position: relative;
}
.child {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
}
```

> tips: 存在 css3 兼容性问题，定宽兼容性良好。

#### 2.3 flex + align-items

```css
.parent {
  display: flex;
  align-items: center;
}
```

### 3. 水平垂直居中

![](https://camo.githubusercontent.com/30bc99e065ab47da716f4ddedda190679c12e7b1/687474703a2f2f75706c6f61642d696d616765732e6a69616e7368752e696f2f75706c6f61645f696d616765732f313439343930382d373934623130313863353564656361612e706e673f696d6167654d6f6772322f6175746f2d6f7269656e742f7374726970253743696d61676556696577322f322f772f31323430)

#### 3.1 inline-block + table-cell + text-align + vertical-align

```css
.parent {
  text-align: center;
  display: table-cell;
  vertical-align: middle;
}
.child {
  display: inline-block;
}
```

> tips: 兼容至 IE8

#### 3.2 absolute + transform

```css
.parent {
  position: relative;
}
.child {
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
}
```

#### 3.3 flex

```css
.parent {
  display: flex;
  justify-content: center;
  align-items: center;
}
```

### 1. 一列定宽，一列自适应

![](https://camo.githubusercontent.com/0dc97e4665a7f4570e43649dd1a437efd5e655a4/687474703a2f2f75706c6f61642d696d616765732e6a69616e7368752e696f2f75706c6f61645f696d616765732f313439343930382d363439373838633039646435386634352e706e673f696d6167654d6f6772322f6175746f2d6f7269656e742f7374726970253743696d61676556696577322f322f772f31323430)

#### 1.1 float + margin

```css
.left {
  float: left;
  width: 100px;
}
.right {
  margin-left: 120px;
}
```

> tips: 此方案对于定宽布局比较好，不定宽布局推荐方案 1.2

#### 1.2 float + overflow

```css
.left {
  float: left;
  width: 100px;
  margin-right: 20px;
}
.right {
  overflow: hidden;
}
```

> tips: 兼容性极好，此方案不管是多列定宽或是不定宽都可以完美实现,且可以实现等高布局。

#### 1.3 table

```css
.parent {
  display: table;
  width: 100%;
  table-layout: fixed;
}
.left,
.right {
  display: table-cell;
}
.left {
  width: 100px;
  padding-right: 20px;
}
```

#### 1.4 flex

```css
.parent {
  display: flex;
}
.left {
  width: 100px;
  padding-right: 20px;
}
.right {
  flex: 1;
}
```

### 2. 多列定宽，一列自适应

![](https://camo.githubusercontent.com/e2662a2d218c341251b6ca690757ea5663a37cdd/687474703a2f2f75706c6f61642d696d616765732e6a69616e7368752e696f2f75706c6f61645f696d616765732f313439343930382d626364366538623130343466383961342e706e673f696d6167654d6f6772322f6175746f2d6f7269656e742f7374726970253743696d61676556696577322f322f772f31323430)

#### 2.1 float + overflow

```css
.left,
.center {
  float: left;
  width: 100px;
  margin-right: 20px;
}
.right {
  overflow: hidden;
}
```

#### 2.2 table

```css
.parent {
  display: table;
  width: 100%;
  table-layout: fixed;
}
.left,
.center,
.right {
  display: table-cell;
}
.right {
  width: 100px;
  padding-right: 20px;
}
```

#### 2.3 flex

```css
.parent {
  display: flex;
}
.left,
.center {
  width: 100px;
  padding-right: 20px;
}
.right {
  flex: 1;
}
```

### 3. 一列不定宽，一列自适应

![](https://camo.githubusercontent.com/5d8c67b01656261f16a4173386d8fa9bd0a857bf/687474703a2f2f75706c6f61642d696d616765732e6a69616e7368752e696f2f75706c6f61645f696d616765732f313439343930382d636165313461633532626537343431332e706e673f696d6167654d6f6772322f6175746f2d6f7269656e742f7374726970253743696d61676556696577322f322f772f31323430)

#### 3.1 float + overflow

```css
.left {
  float: left;
  margin-right: 20px;
}
.right {
  overflow: hidden;
}
.left p {
  width: 200px;
}
```

#### 3.2 table

```css
.parent {
  display: table;
  width: 100%;
}
.left,
.right {
  display: table-cell;
}
.left {
  width: 0.1%;
  padding-right: 20px;
}
.left p {
  width: 200px;
}
```

#### 3.3 flex

```css
.parent {
  display: flex;
}
.left {
  margin-right: 20px;
}
.right {
  flex: 1;
}
.left p {
  width: 200px;
}
```

### 4. 多列不定宽，一列自适应

![](https://camo.githubusercontent.com/1ce417134bd2de08834c3135789ee46793cbc9e2/687474703a2f2f75706c6f61642d696d616765732e6a69616e7368752e696f2f75706c6f61645f696d616765732f313439343930382d353430663462383466306334363731382e706e673f696d6167654d6f6772322f6175746f2d6f7269656e742f7374726970253743696d61676556696577322f322f772f31323430)

#### 4.1 float + overflow

```css
.left,
.center {
  float: left;
  margin-right: 20px;
}
.right {
  overflow: hidden;
}
.left p,
.center p {
  width: 100px;
}
```

### 5. 等分

![](https://camo.githubusercontent.com/c307ee586dbb99e2c9d2a769120d29afca93690a/687474703a2f2f75706c6f61642d696d616765732e6a69616e7368752e696f2f75706c6f61645f696d616765732f313439343930382d636261613630396536343764643164652e6a70673f696d6167654d6f6772322f6175746f2d6f7269656e742f7374726970253743696d61676556696577322f322f772f31323430)

#### 5.1 float + margin

```css
.parent {
  margin-left: -20px;
}
.column {
  float: left;
  width: 25%;
  padding-left: 20px;
  box-sizing: border-box;
}
```

#### 5.2 table + margin

```css
.parent-fix {
  margin-left: -20px;
}
.parent {
  display: table;
  width: 100%;
  table-layout: fixed;
}
.column {
  display: table-cell;
  padding-left: 20px;
}
```

#### 5.3 flex

```css
.parent {
  display: flex;
}
.column {
  flex: 1;
}
.column + .column {
  margin-left: 20px;
}
```

### 6. 等高

![](https://camo.githubusercontent.com/87df1db7ae76df03c01ffc456a399dae95328142/687474703a2f2f75706c6f61642d696d616765732e6a69616e7368752e696f2f75706c6f61645f696d616765732f313439343930382d306537616538613332303630666430362e6a70673f696d6167654d6f6772322f6175746f2d6f7269656e742f7374726970253743696d61676556696577322f322f772f31323430)

#### 6.1 float + overflow

```css
.parent {
  overflow: hidden;
}
.left,
.right {
  padding-bottom: 9999px;
  margin-bottom: -9999px;
}
.left {
  float: left;
  width: 100px;
}
.right {
  overflow: hidden;
}
```

#### 6.2 table

```css
.parent {
  display: table;
  width: 100%;
}
.left {
  display: table-cell;
  width: 100px;
  margin-right: 20px;
}
.right {
  display: table-cell;
}
```

#### 6.3 flex

```css
.parent {
  display: flex;
  width: 100%;
}
.left {
  width: 100px;
}
.right {
  flex: 1;
}
```

## 并排等分，单排对其靠左布局

![](https://camo.githubusercontent.com/0fc7b95367a18f96e0e0d5205a33ce6ccee85216/68747470733a2f2f643236647a786f616f36693368682e636c6f756466726f6e742e6e65742f6974656d732f33533436334933423343317831693062303631352f53637265656e2532305265636f7264696e67253230323031372d30392d3034253230617425323031322e35332532302545342542382538422545352538442538382e6769663f763d6462666331666465)

### flex

```css
.main {
  display: flex;
  flex-flow: row wrap;
  justify-content: space-between;
}
.item {
  display: inline-block;
}
.empty {
  height: 0;
  visibility: hidden;
}
```

## 参考文档
1. [【布局】CSS布局方案](https://github.com/zwwill/blog/issues/14)
