### ISSUE TITLE
如何让一个长宽未知的元素在水平和垂直方向都居中之N种方法的总结 

### ISSUE THREAD

**Issue by ly2011** [ly2011/blog#95]
- 1. 利用 flex

设置 display: flex。利用 flex 的align-items: center 让其垂直居中，利用 justify-content: center 让其水平居中。

```css
.parent {
  height:400px;
  width:400px;
  border:1px solid red;
  display: flex;
  align-items: center;
  justify-content:center;
}
.child {
  border: 1px solid blue;
}
```

- 2. 利用 table

设置 display: table。利用 text-align: center 让其水平居中，利用 vertical-align: middle 让其垂直居中。

```css
.parent {
  height: 400px;
  width: 400px;
  border: 1px solid red;
  display: table-cell;
  text-align: center;
  vertical-align: middle;
}
.child {
  border: 1px solid blue;
}
```

- 3. 利用 transform

设置 position: relative。让子元素相对定位，相对父元素左侧和上侧为父元素的百分之50然后再利用 transform: translate(-50%, -50%) 回移百分之50。

```css
.parent {
  height: 400px;
  width: 400px;
  border: 1px solid red;
}
.child {
  border: 1px solid blue;
  position: relative;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
}
```

- 4. 利用 grid

设置 grid 布局。利用 align-item: center 让其垂直居中，利用 justify-content: center 让其水平居中。

```css
.parent {
  border: 1px solid red;
  height: 400px;
  width: 400px;
  display: grid;
  align-items: center;
  justify-content: center;
}
.child {
  border: 1px solid blue;
}
```

- 5. 利用 margin: auto

设置 position: absolute 之后，设置距离父元素四边的距离都为0,然后设置 margin: auto。

```css
.parent {
  position: relative;
  border: 1px solid red;
  width: 400px;
  height: 400px;
}
.child {
  border: 1px solid blue;
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  margin: auto;
}
```
